main: pl.trollcraft.lucyutils.LucyUtils
name: LucyUtils
author: LucyferMS
version: 1.0-SNAPSHOT
api-version: 1.13
depend:
  - FastAsyncWorldEdit
  - WorldGuard
  - Multiverse-Core
commands:
  lucyutils:
    usage: /lu
  report:
    usage: /report
  pomoc:
    usage: /pomoc
